### ISSUE TITLE
can you make a javafx.graphics.win-es2.jar on javafx21?

### ISSUE THREAD

**Issue by qq1053831109** [husker-dev/openglfx#42]
https://github.com/husker-dev/openglfx/raw/master/libs/javafx.graphics.win-es2.jar is 404

any in InteropImpl mode. some time i will get an exit code and no crash log file.

the exit code is: -1073741819 (0xC0000005)

so may by es is stable。

**Comment by husker-dev** [comment]
I don't quite understand the point of the question.

---
```javafx.graphics.win-es2.jar``` has been temporarily removed because it is not directly related to openglfx. 
I wanted to make a separate repository to compile the file automatically from javafx repository.

Currently it is not used in openglfx anyway. And was used only for testing the ES2 pipeline on windows.

---

0xC0000005 (memory access violation) most likely occurs in the lwjgl part. Check if the opengl context is not lost somewhere when calling GL functions.

**Comment by husker-dev** [comment]
GLES for Windows now can be downloaded from https://github.com/husker-dev/jfx-win-es2 in Actions tab

Latest build:
https://github.com/husker-dev/jfx-win-es2/suites/17000985716/artifacts/971064439

**Comment by qq1053831109** [comment]
good. the opengl Shared is fast. dx only has 50fps in 4k screen。now just need one Multithreaded renderer.and sync with javafx

**Comment by qq1053831109** [comment]
the Latest build is not work:
https://github.com/husker-dev/jfx-win-es2/suites/17000985716/artifacts/971064439

Graphics Device initialization failed for :  es2
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)

**Comment by streamingdv** [comment]
@qq1053831109 here is a working version

https://github.com/streamingdv/jfx-win-es2/actions/runs/6686498529

It's just a quick hack which just uses my forked jfx-21 repo with the required "_INCLUDE_ES2 changes_" in the build.gradle. Ideally this should be done automatically in the github action script.

@husker-dev good idea with the repo and the github action script but I think you forgot to configure the build.gradle of the jfx repo in order to build "javafx.graphics.jar" with es2?
