### ISSUE TITLE
4.05 Still Flower Screen！

### ISSUE THREAD

**Issue by qq1053831109** [husker-dev/openglfx#78]
4.05 Still Flower Screen。
Asynchronous performance is worrying。
It is recommended to do multithreading on the basis of synchronization。
Is there a method that doesn't require copying textures？

**Comment by qq1053831109** [comment]
Automatically discard the current frame when the gl drawing time expires. Wait for the gl drawing speed to exceed 10 fps before starting synchronization. Because in some cases, gl may get stuck in the loading scene, at which point fx does not need to block and wait for gl. Fx needs to display the loading circle animation at this time!

**Comment by qq1053831109** [comment]
The asynchronous drawing board of 4.0.5 is many times slower than that of 4.0.0

**Comment by husker-dev** [comment]
The asynchronous method implies two OpenGL contexts (for drawing and outputting an image). Since in OpenGL you cannot send framebuffer between contexts, you have to use textures. 
The method you propose is not entirely asynchronous.

I plan to rewrite this logic in the near future using built-in GLsync mechanism, but I’m very busy right now, so I don't have much time for this.
I'll get it to work today, and maybe over the weekend. There's a lot of work to be done.

**Comment by husker-dev** [comment]
Check the new release 4.1.0.
If the problem is not solved, then reopen the issue
