### ISSUE TITLE
NVDXInterop crash upon calling wglDXRegisterObjectNV

### ISSUE THREAD

**Issue by streamingdv** [husker-dev/openglfx#80]
**Describe the bug**
I'm currently in the middle of a closed beta test and a user of mine reported a bug when using the OpenGLFX rendering engine. It immediately crashes upon startup of the stream.

**To Reproduce**
Difficult seems to be driver or device specific. Here are some crashlogs

[Crashlogs.zip](https://github.com/husker-dev/openglfx/files/15051903/Crashlogs.zip)

It seems it is DirectX related, I asked him to use the OpenGL pipeline on Windows (which is supported by my application). Will report back if the crash also happens via the OpenGL pipeline but I guess not.

**Environment:**
 - OS:
1. Nvidia gtx 1650 mobile
2. Ryzen 5 5600h
3. Windows 11 Pro 23H2

 - openglfx version: 4.0.5

**Comment by husker-dev** [comment]
Interesting. I think I should also do a little functionality testing when checking NvDxInterop support to rule out any driver or hardware issues. 

I'll see what I can do about it, but right now all my time is spent upgrading offscreen-jgl (now called “grapl”) to make it possible to update openglfx in future

**Comment by streamingdv** [comment]
Thanks, yes no worries. Keep me updated.
I will report back if I got some news.

**Comment by streamingdv** [comment]
@husker-dev yes the OpenGL pipeline seems to work fine according to the feedback I got from my beta tester.

**Comment by streamingdv** [comment]
[hs_err_pid23372.txt](https://github.com/husker-dev/openglfx/files/15285671/hs_err_pid23372.txt)

Another crash report from a user, happening on a AMD Ryzen 5 5500U with Radeon Graphics device.

**Comment by streamingdv** [comment]
@husker-dev are there any news? I got a few more bug reports and all of them seem to use some kind of Radeon Graphics device. My application also offers additional rendering pipelines so I have workarounds available but would be cool if this could be fixed somehow.

**Comment by husker-dev** [comment]
@streamingdv 
Hi, currently busy with my job and also the project [grapl](https://github.com/husker-dev/grapl) that we use. 
I plan to work on openglfx soon, but I won't give exact dates. It might be in the next few weeks

**Comment by streamingdv** [comment]
All good, thanks for the status update 👍

**Comment by husker-dev** [comment]
@streamingdv, some updates:

Swap buffers
---
I made a good asynchronous algorithm that will have something called "Swap buffers". 
Also, I will remove synchronous rendering, because better option will be configuration with one swap buffer.

NVDXInterop has already been rewritten to support them.

New interop type
---

I've been trying to implement texture sharing from **DirectX 9** to **OpenGL** via DXGI handles for the last three days. 

I managed to do it via a **DirectX 11** proxy.
It used [EXT_external_objects](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_external_objects.txt) and [EXT_external_objects_win32](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_external_objects_win32.txt) on OpenGL side. 

Most of the logic is taken from here: 
- https://github.com/malstraem/vulkan-interop-directx/issues/2#issuecomment-1943740488
- [Similar example on Stack Overflow](https://stackoverflow.com/questions/71108346/how-to-use-glimportmemorywin32handleext-to-share-an-id3d11texture2d-keyedmutex-s)

I'll make this a priority choice over [wgl_nv_dx_interop](https://registry.khronos.org/OpenGL/extensions/NV/WGL_NV_DX_interop.txt) because it consumes less GPU resources and should also be well supported on AMD GPU.


> I'll upload the code soon

**Comment by husker-dev** [comment]
It looks like I can do it without DirectX 11. It seems to work too

**Comment by streamingdv** [comment]
Once the new version is ready I can definitely offer to test it on a few Windows/ Linux machines. If everything works I can invite some users of my application to test an beta release of my app bundled with the new OpenGLFX lib to get some feedback.

**Comment by husker-dev** [comment]
Check the new release 4.1.0.
If the problem is not solved, then reopen the issue
